Vector3 is now immutable
pmmp/Math pull request #90
Opened 2023-11-19 09:48 UTC by Dhaiven

Complete #88 just for Vector3

2024-02-28 16:28 UTC, dktapps commented
This requires a PHP 8.2 minimum

2024-05-12 16:56 UTC, Dhaiven commented
> This requires a PHP 8.2 minimum

Yes but pocketmine now support PHP 8.2

2024-05-13 09:24 UTC, dktapps commented
Supporting 8.2 != minimum 8.2

2024-05-13 10:06 UTC, Dhaiven commented
> Supporting 8.2 != minimum 8.2

When pocketmine will oblige PHP 8.2?

2024-05-13 10:37 UTC, dktapps commented
Not before PM6.

2024-12-02 00:27 UTC, dktapps requested changes
This PR is doing a ton of unnecessary changes

2024-12-02 00:27 UTC, dktapps commented on src/Vector3.php
> +		protected float|int $z
I don't like this change. The whole point of making the class readonly is to allow direct access to its fields without mutability issues.

2024-12-02 13:30 UTC, Dhaiven commented
may be add in this pr immutable for Vector2, AABB... because the changes of this pr is light

2024-12-02 15:40 UTC, dktapps commented
No. Making a PR 101: Do not do multiple changes at once.

2024-12-02 15:47 UTC, Dhaiven commented
ok

2024-12-02 16:09 UTC, dktapps commented
You need to drop PHP 8.1 from composer.json and GitHub Actions

2024-12-02 17:56 UTC, Dhaiven commented
Like this ?

2024-12-02 21:09 UTC, dktapps commented
Yep

2024-12-02 21:09 UTC, dktapps approved these changes, later dismissed

2024-12-02 21:22 UTC, merged