AxisAlignedBB is now immutable
pmmp/Math pull request #95
Opened 2024-12-03 18:00 UTC by Dhaiven

Like #90 but for AABB, fix #88

2024-12-03 18:23 UTC, dktapps commented
I'd prefer if we kept the `*Copy` versions. That way, only the people using the mutable functions will get their code broken.

2024-12-03 18:27 UTC, Dhaiven commented
I said the same thing to myself but i think it's better to keep logic between Vector & AABB.
Vector is immutable and don't have a `copy` on the name of function return a new vector like `add` so i thinks it's better to do the same in AABB

2024-12-03 18:28 UTC, Dhaiven commented
Maybe add `@deprecated` for `*Copy` versions and remove them for pmmp 7 for exemple

2024-12-03 18:33 UTC, dktapps commented
> I said the same thing to myself but i think it's better to keep logic between Vector & AABB. Vector is immutable and don't have a `copy` on the name of function return a new vector like `add` so i thinks it's better to do the same in AABB

Vector isn't relevant to this code. Totally different API. If anything, I'd've preferred `Vector` methods to have `Copy` suffixes to make it clear how they behave. But again, not relevant.

> Maybe add `@deprecated` for `*Copy` versions and remove them for pmmp 7 for exemple

I don't want to penalize correct code. There's no point doing a deprecation like that, it's just delaying the inevitable.
Either we keep them permanently, or we remove them now.

If we remove the `*Copy()` variations
- bad (mutable) code silently gets a behavioural BC break and possibly stops working
- good (immutable) code blows up and has to be refactored for no good reason

If we just remove the mutable variants and keep `*Copy()`
- bad (mutable) code blows up and has to be refactored (fine)
- good (immutable) code is unaffected

2024-12-03 19:37 UTC, dktapps requested changes
There are now many incorrect `@return $this` doc comments

2024-12-03 19:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	public function trimedCopy(Facing $face, float $distance) : AxisAlignedBB{
typo

2024-12-03 19:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +		};
The original code was more readable. Better to convert it to use local vars and then `return new AxisAlignedBB(...)` at the end.

2024-12-03 19:37 UTC, dktapps commented on src/AxisAlignedBB.php
>  	 * @return $this
This is no longer correct

2024-12-03 20:20 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns an contracted clone of this AxisAlignedBB.
```suggestion
	 * Returns a contracted clone of this AxisAlignedBB.
```

2024-12-03 20:22 UTC, dktapps requested changes
Looking better, but I think the docs could be cleaned up

```
Outsets the bounds of this AxisAlignedBB by the specified X, Y and Z.

Returns an expanded clone of this AxisAlignedBB.
```
can be reworded like
```
Returns a copy of the AxisAlignedBB with bounds outset by the specified X, Y and Z.
```
etc

2024-12-04 21:37 UTC, dktapps requested changes

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds offset by the specified X, Y and Z.
```suggestion
	 * Returns a copy of the AxisAlignedBB offset by the specified X, Y and Z.
```

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds offset in the given direction by the specified distance.
```suggestion
	 * Returns a copy of the AxisAlignedBB offset in the given direction by the specified distance.
```

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds extended in the given direction.
Summary should be placed above any @param or @return tags

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds extended in the given direction.
`Returns a copy of the AxisAlignedBB extended in the given direction.` would be more to the point also

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds trimmed in the given direction.
I don't think this is needed. Saying that it's the inverse of extend() is enough.

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Inverse of extend().
```suggestion
	 * Inverse of extendedCopy().
```

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds stretched along the given axis.
This should be above the @param tag, also `with bounds` seems superfluous

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Returns a copy of the AxisAlignedBB with bounds squashed along the given axis.
Unnecessary, saying it's inverse of stretch is sufficient

2024-12-04 21:37 UTC, dktapps commented on src/AxisAlignedBB.php
> +	 * Inverse of stretch().
```suggestion
	 * Inverse of stretchedCopy().
```

2024-12-09 17:35 UTC, dktapps approved these changes

2024-12-09 17:35 UTC, merged